# 🔢 Módulo 6 — NumPy: Fundamentos

NumPy es la librería base para cálculo numérico en Python.
Ofrece:
- Arrays de alta eficiencia
- Operaciones vectorizadas
- Broadcasting
- Manipulación avanzada de datos numéricos

Este notebook cubre los fundamentos que necesitarás para análisis de datos, machine learning, ETL, simulaciones, etc.

---
## 1️⃣ Crear arrays de NumPy

Arrays básicos:

In [35]:
import numpy as np

a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
c = np.arange(1,31)

a, b, c

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]))

Creación rápida de estructuras:

In [ ]:
np.zeros((2,3)), np.ones((2,2)), np.arange(0,10,2), np.linspace(0,1,5)

---
## 2️⃣ Propiedades de un array

- `ndim`: número de dimensiones
- `shape`: forma (filas, columnas)
- `size`: número total de elementos
- `dtype`: tipo de dato


In [6]:
x = np.array([[10,20.3,30,"hola",4],[40,50,60,"ale",4]])
x.ndim, x.shape, x.size, x.dtype

(2, (2, 5), 10, dtype('<U32'))

---
## 3️⃣ Operaciones vectorizadas

Evitan bucles explícitos y son extremadamente rápidas.

In [7]:
v = np.array([1,2,3])
v*10, v+5, v**2

(array([10, 20, 30]), array([6, 7, 8]), array([1, 4, 9]))

Comparación con bucles de Python:

In [8]:
%timeit [x*2 for x in range(1000000)]
%timeit np.arange(1000000)*2

48.4 ms ± 1.89 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
762 μs ± 63.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


---
## 4️⃣ Broadcasting

NumPy puede operar arrays de distinta forma si son compatibles.

Ejemplo simple:

In [9]:
mat = np.array([[1,2,3],[4,5,6]])
mat + np.array([10,20,30])

array([[11, 22, 33],
       [14, 25, 36]])

---
## 5️⃣ Tipos (`dtype`)

NumPy permite controlar el tipo exacto:

In [16]:
y=np.array([1,2,3], dtype=np.float32), np.array([1,2,3], dtype=np.int8)

y

(array([1., 2., 3.], dtype=float32), array([1, 2, 3], dtype=int8))

---
## 6️⃣ Ejercicio práctico

### 🧩 Ejercicio
Crea un array de números del 1 al 20.
- Consigue todos los valores pares usando slicing
- Multiplica esos pares por 3 (vectorizado)
- Cambia el tipo del array resultante a `float32`

Escribe tu solución abajo:

In [49]:
# Tu solución aquí
import numpy as np
a = np.arange(1,21)
pares = a[a%2==0]
pares *= 3
pares.astype(np.float32)

a, pares



(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20]),
 array([ 6, 12, 18, 24, 30, 36, 42, 48, 54, 60]))

In [48]:
# ejemplos slicing

pares[1:3],pares[::2]


(array([12, 18]), array([ 6, 18, 30, 42, 54]))

---
## ✅ Solución (oculta)

<details>
<summary>Mostrar solución</summary>

```python
x = np.arange(1,21)
pares = x[x%2==0]
res = pares * 3
res.astype(np.float32)
```
</details>