# 🧮 Módulo 6 — NumPy: Álgebra Lineal

NumPy incluye el módulo `numpy.linalg`, con herramientas para:

- Producto punto
- Multiplicación de matrices
- Matrices transpuestas
- Determinantes
- Matrices inversas
- Autovalores y autovectores
- Resolución de sistemas lineales

Este notebook cubre los fundamentos para análisis estadístico, ML, física, economía y más.

---
## 1️⃣ Producto punto (`dot`)

Para vectores:

In [22]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
#             1*4+2*5+3*6
#             4+10+18=32 
np.dot(a, b),a @ b


(np.int64(32), np.int64(32))

---
## 2️⃣ Multiplicación matricial

Para matrices 2D, `@` es equivalente a `dot()`.

In [6]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

A @ B

array([[19, 22],
       [43, 50]])

---
## 3️⃣ Traspuesta

`.T` devuelve una vista transpuesta:

In [9]:
A,A.T

(array([[1, 2],
        [3, 4]]),
 array([[1, 3],
        [2, 4]]))

---
## 4️⃣ Determinante

Usando `numpy.linalg.det`:

In [13]:
np.linalg.det(A)

np.float64(-2.0000000000000004)

---
## 5️⃣ Inversa de una matriz

`numpy.linalg.inv()` calcula la inversa si existe.

In [14]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

---
## 6️⃣ Autovalores y autovectores

Muy utilizados en PCA, análisis espectral, dinámica, optimización...

In [15]:
valores, vectores = np.linalg.eig(A)
valores, vectores

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

---
## 7️⃣ Resolver sistemas lineales

Resolver:
```
3x + y  = 9
x + 2y = 8
```

In [16]:
coef = np.array([[3,1],[1,2]])
cons = np.array([9,8])

np.linalg.solve(coef, cons)

array([2., 3.])

---
## 8️⃣ Ejemplo real: regresión lineal (mínimos cuadrados)

Resolver `Ax ≈ b` mediante pseudoinversa:

In [17]:
x = np.array([1,2,3,4])
y = np.array([2,4,5,4])

A = np.vstack([x, np.ones(len(x))]).T
coef, resid, *_ = np.linalg.lstsq(A, y, rcond=None)

coef  # pendiente y ordenada

array([0.7, 2. ])

---
## 9️⃣ Ejercicio práctico

Dada la matriz:
```python
M = np.array([[2,1],[5,7]])
```

### 🧩 Objetivos
1. Calcula el determinante
2. Calcula la inversa
3. Verifica que `M @ M_inv ≈ I`
4. Halla autovalores y autovectores

Escribe tu solución aquí:

In [ ]:
# Tu solución aquí
M = np.array([[2,1],[5,7]])
det = np.linalg.det(M)
inv = np.linalg.inv(M)
ident = M @ inv
vals, vecs =np.linalg.eig(M)


M,det,inv,ident, vals, vecs

(array([[2, 1],
        [5, 7]]),
 np.float64(9.000000000000002),
 array([[ 0.77777778, -0.11111111],
        [-0.55555556,  0.22222222]]),
 array([[1.00000000e+00, 0.00000000e+00],
        [1.11022302e-16, 1.00000000e+00]]),
 array([1.14589803, 7.85410197]),
 array([[-0.76039797, -0.16838141],
        [ 0.6494574 , -0.98572192]]))

---
## ✅ Solución (oculta)

    
<details>
<summary>Mostrar solución</summary>

```python
M = np.array([[2,1],[5,7]])

det = np.linalg.det(M)
inv = np.linalg.inv(M)
ident = M @ inv
eigvals, eigvecs = np.linalg.eig(M)

det, inv, ident, eigvals, eigvecs
```
</details>