# 🧪 Laboratorio — NumPy Completo

Este laboratorio reúne todo lo aprendido en el módulo NumPy:

- Creación y propiedades de arrays
- Formas y `reshape`
- Indexación básica y avanzada
- Copias vs vistas
- Álgebra lineal
- Ejercicios integrados de análisis numérico

Completa cada sección antes de ver la solución.

---
## 1️⃣ Fundamentos — Crear arrays

### 🧩 Ejercicio
Crea un array `x` con los números del 1 al 20.
- Obtén sus dimensiones (`ndim`), forma (`shape`) y tipo (`dtype`).
- Convierte el array a `float32`.

Escribe tu solución aquí:

In [4]:
import numpy as np
# Tu solución aquí
x = np.arange(1,21)
x.astype(np.float32)
x,x.ndim, x.shape, x.dtype


(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20]),
 1,
 (20,),
 dtype('int64'))

---
## 2️⃣ Formas y `reshape`

### 🧩 Ejercicio
Con el array `x`:
1. Convierte `x` en una matriz 4×5
2. Aplánala usando `ravel()`
3. Aplánala usando `flatten()`

Compara si las dos versiones comparten memoria.

In [5]:
# Tu solución aquíf
x=x.reshape(4,5)

x,x.ravel(),x.flatten()

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20]))

---
## 3️⃣ Indexación básica, slicing y booleana

### 🧩 Ejercicio
Dada la matriz:
```python
m = np.arange(1,17).reshape(4,4)
```
Haz lo siguiente:
1. Extrae la segunda fila
2. Extrae la segunda columna
3. Extrae el bloque central 2×2
4. Obtén los números mayores a 10 usando indexación booleana
5. Usa fancy indexing para obtener la diagonal inversa

Escribe aquí tu código:

In [6]:
m = np.arange(1,17).reshape(4,4)
# Tu solución aquí
f2 = m[1]
c2 = m[:,1]
c = m[1:3,1:3]
m10 = m[m>10]
di=m[[3,2,1,0],[0,1,2,3]]

m,f2,c2,c,m10,di


(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([5, 6, 7, 8]),
 array([ 2,  6, 10, 14]),
 array([[ 6,  7],
        [10, 11]]),
 array([11, 12, 13, 14, 15, 16]),
 array([13, 10,  7,  4]))

---
## 4️⃣ Copias vs Vistas — Comportamiento real

### 🧩 Ejercicio
Usa el mismo array `m`:

1. Obtén una vista de la primera fila y modifica un valor
2. Comprueba si `m` cambia
3. Obtén una copia de esa fila y modifica un valor
4. Comprueba si `m` cambia
5. Usa `np.shares_memory` para documentar el resultado

Escribe tu solución aquí:

In [7]:
# Tu solución aquí
f1 = m[0].copy()
f1[2]=99
m,f1


(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([ 1,  2, 99,  4]))

---
## 5️⃣ Álgebra lineal — ejercicios aplicados

### 🧩 Problema A — Matriz cuadrada
Dada:
```python
A = np.array([[3,1],[2,4]])
```
Calcula:
1. Determinante
2. Inversa
3. Autovalores y autovectores
4. Verifica que `A @ inv ≈ I`

### 🧩 Problema B — Sistema lineal
Resuelve:
```
2x + y = 10
x + 3y = 13
```
Escribe aquí tu solución:

In [ ]:
# Tu solución aquí
A = np.array([[3,1],[2,4]])
d=np.linalg.det(A)
i=np.linalg.inv(A)
autv, auto=np.linalg.eig(A)
ident = A @ i

d,i,autv,auto,ident

(np.float64(10.000000000000002),
 array([[ 0.4, -0.1],
        [-0.2,  0.3]]),
 array([2., 5.]),
 array([[-0.70710678, -0.4472136 ],
        [ 0.70710678, -0.89442719]]),
 array([[1., 0.],
        [0., 1.]]))

---
## 6️⃣ Ejercicio integrador — Dataset numérico

Dado un dataset simulado (puntuaciones por examen):
```python
notas = np.array([
    [7,8,9],
    [5,6,7],
    [9,9,10],
    [4,5,6]
])
```
### 🧩 Objetivo
1. Calcula la media por alumno
2. Calcula la media por examen
3. Obtén una matriz normalizada restando la media por examen
4. Calcula el vector de varianzas por examen
5. Extrae los valores mayores a 8 usando boolean indexing

Escribe aquí tu trabajo:

In [18]:
notas = np.array([
    [7,8,9],
    [5,6,7],
    [9,9,10],
    [4,5,6]
])

# Tu solución aquí
media_alumno = notas.mean(axis=1)
media_examen = notas.mean(axis=0)
normal = notas - media_examen
vari = notas.var(axis=0)
mas8= notas[notas>8]

media_alumno, media_examen, normal, vari, mas8


(array([8.        , 6.        , 9.33333333, 5.        ]),
 array([6.25, 7.  , 8.  ]),
 array([[ 0.75,  1.  ,  1.  ],
        [-1.25, -1.  , -1.  ],
        [ 2.75,  2.  ,  2.  ],
        [-2.25, -2.  , -2.  ]]),
 array([3.6875, 2.5   , 2.5   ]),
 array([ 9,  9,  9, 10]))

---
## ✅ Solución completa (oculta)

<details>
<summary>Mostrar soluciones</summary>

### ✔️ Fundamentos
```python
x = np.arange(1,21)
x.ndim, x.shape, x.dtype
x = x.astype(np.float32)
```

### ✔️ Reshape
```python
m = x.reshape(4,5)
r1 = m.ravel()
r2 = m.flatten()
np.shares_memory(m, r1), np.shares_memory(m, r2)
```

### ✔️ Indexación
```python
fila2 = m[1]
col2 = m[:,1]
bloque = m[1:3,1:3]
mayores10 = m[m>10]
diag_inv = m[[0,1,2,3],[3,2,1,0]]
```

### ✔️ Copias vs vistas
```python
v = m[0]
v[0] = 999

c = m[0].copy()
c[1] = 555

np.shares_memory(m, v), np.shares_memory(m, c)
```

### ✔️ Álgebra lineal
```python
A = np.array([[3,1],[2,4]])
det = np.linalg.det(A)
inv = np.linalg.inv(A)
eigvals, eigvecs = np.linalg.eig(A)
ident = A @ inv

coef = np.array([[2,1],[1,3]])
cons = np.array([10,13])
sol = np.linalg.solve(coef, cons)
```

### ✔️ Dataset
```python
media_alumno = notas.mean(axis=1)
media_examen = notas.mean(axis=0)
normalizada = notas - media_examen
varianzas = notas.var(axis=0)
mayores8 = notas[notas>8]
```
</details>